force-app/main/default/objects/Warranty__c/Warranty__c.object-meta.xml
<CustomObject>
    <label>보증</label>
    <nameField>
        <label>보증 이름</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>보증</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warranty__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>자동 수식 필드</description>
    <formula>ADDMONTHS( Registration_Date__c , Warranty_Period__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>만료 일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Warranty__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <description>보증 시작 일자</description>
    <label>등록 일자</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Warranty__c/fields/Warranty__c.field-meta.xml
<CustomField>
    <fullName>Warranty__c</fullName>
    <displayFormat>W-{0000}</displayFormat>
    <label>Warranty_ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Warranty__c/fields/Warranty_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Mileage__c</fullName>
    <label>보증 주행거리</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warranty__c/fields/Warranty_Period__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Period__c</fullName>
    <label>보증 개월 수</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warranty__c/fields/Warranty_Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>관련 고객</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>보증</relationshipLabel>
    <relationshipName>Warranty_Related_Account_btw5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warranty__c/fields/Warranty_Related_Asset__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Related_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>연결 자산</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>보증</relationshipLabel>
    <relationshipName>Warranty_Related_Asset_2DZ3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WarrantyController.cls
public with sharing class WarrantyController {
    @AuraEnabled(cacheable=true)
    public static Warranty__c getWarrantyByAccountId(Id accountId) {
        return [
            SELECT Name, Registration_Date__c, Expiration_Date__c, Warranty_Period__c,
                   Warranty_Mileage__c,
                   Warranty_Related_Asset__r.Name,
                   Warranty_Related_Account__r.Name
            FROM Warranty__c
            WHERE Warranty_Related_Account__c = :accountId
            LIMIT 1
        ];
    }
}