force-app/main/default/objects/Flagship_Store__c/Flagship_Store__c.object-meta.xml
<CustomObject>
    <label>플래그십 스토어</label>
    <nameField>
        <label>플래그십 스토어 이름</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>플래그십 스토어</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flagship_Store__c/fields/AvailableModles__c.field-meta.xml
<CustomField>
    <fullName>AvailableModles__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>시승 가능 모델</label>
    <referenceTo>VehicleModel__c</referenceTo>
    <relationshipLabel>플래그십 스토어</relationshipLabel>
    <relationshipName>FlagshipStore</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flagship_Store__c/fields/Road_name__c.field-meta.xml
<CustomField>
    <fullName>Road_name__c</fullName>
    <description>도로명주소 값</description>
    <label>도로명 주소</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flagship_Store__c/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <description>플래그십 스토어 위도, 경도 표시</description>
    <label>플래그십 위치</label>
    <scale>8</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/classes/TestDriveLocationController.cls
public with sharing class TestDriveLocationController {
    
    @AuraEnabled(cacheable=true)
    public static List<Flagship_Store__c> getFlagshipStoresWithLocation(String carName) {
        List<Flagship_Store__c> allStores = [
            SELECT Id, Name, Road_name__c, Store_Location__Latitude__s, Store_Location__Longitude__s, Store_Location__c
            FROM Flagship_Store__c
            WHERE AvailableModles__c = :'a0SgL0000005e4rUAA'
        ];

        List<Flagship_Store__c> storesWithLocation = new List<Flagship_Store__c>();
        for (Flagship_Store__c store : allStores) {
            if (store.Store_Location__Latitude__s != null && store.Store_Location__Longitude__s != null) {
                storesWithLocation.add(store);
            }
        }

        return storesWithLocation;
    
    }
}